Primeira semana
sruinascimento/rtech pull request #2
Opened 2022-09-09 19:32 UTC by sruinascimento

2022-10-20 00:21 UTC, alexandreaquiles commented on src/Validate.java
> +    //Chamar as mensagens de erro, sem precisar passar por parâmetro?
Melhor passar por parâmetro!

2022-10-20 00:26 UTC, alexandreaquiles commented on src/ErrorMessage.java
> +public enum ErrorMessage {
Ficou bom. Uma crítica aqui é que essa enum tende a crescer infinitamente e participar do todos o commits do projeot.

2022-10-20 00:28 UTC, alexandreaquiles requested changes
O conteúdo do `.idea` e `out` não costumamos a versionar. O repo do GitHub deve ficar agnóstico de IDE. Remova e coloque no .gitignore

De resto, está excelente.!

2022-10-21 00:24 UTC, alexandreaquiles approved these changes
Topzera :1st_place_medal:

2022-10-23 20:45 UTC, merged

2022-10-23 20:45 UTC, sruinascimento commented
Desafio concluido: primeira semana ✔️